apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrique-garcia-student-k8s
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrique-garcia-student-k8s
  template:
    metadata:
      labels:
        app: enrique-garcia-student-k8s
    spec:
      serviceAccountName: my-sa
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: enrique-garcia-student-k8s
          image: 934841374016.dkr.ecr.us-west-2.amazonaws.com/enroute-registry:kafka-client-tls-iam